### ISSUE TITLE
В описании задачи указано было сделать через if, switch

### ISSUE THREAD

**Issue by Rainbowdm** [bpm2021/qa_auto#1]
https://github.com/bpm2021/qa_auto/blob/c0ec39195ad732bbc1923a7d5601c45de4266dc9/Lesson_1.java#L74

**Comment by bpm2021** [comment]
if (numMonth == 12 || numMonth == 1 || numMonth == 2) {
            System.out.println("Winter");
        } else if (numMonth == 3 || numMonth == 4 || numMonth == 5) {
            System.out.println("Spring");
        } else if (numMonth == 6 || numMonth == 7 || numMonth == 8) {
            System.out.println("Summer");
        } else if (numMonth == 9 || numMonth == 10 || numMonth == 11) {
            System.out.println("Autumn");
        } else {
            System.out.println("Unknown time of the year");
        }

**Comment by Rainbowdm** [comment]
Добавь в ветку и закинь в репозиторий

**Comment by bpm2021** [comment]
Готово!

**Comment by Rainbowdm** [comment]
Checked
